members/urls.py
from django.urls import path, re_path

from . import views


app_name = 'members'

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^export/csv/$', views.export_data_csv, name='export_data_csv'),
    re_path(r'^export/xls/$', views.export_data_xls, name='export_data_xls'),


    
]

webApplication4/urls.py
from django.contrib import admin
from django.urls import path, include #new
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include ("django.contrib.auth.urls")), #new
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
    path('members/', include('members.urls')),



]

templates/base.html
{% load static %}

<!-- templates/base.html -->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Ali Ali Ali{% endblock %}</title>

    <!-- Bootstrap Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <!-- Custom style -->
    <link rel="stylesheet" href="{% static '/style.css' %}">

</head>

<body>

    <nav class="navbar navbar-fixed-top navigation-bar">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img class="logo" alt="Brand" src="{% static 'img/logo.png' %}">
                </a>
            </div>
            <div>

                {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right nav-links">
                    <li class="a-alike">Welcome {{ user.username }}!</li>
                    <li><a href="{% url 'members:index' %}">Members</a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav navbar-right nav-links">
                    <li class="a-alike">You are not logged in</li>
                    <li><a href="{% url 'login' %}">Log In</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>




    <!-- Collect the nav links, forms, and other content for toggling -->

    <!-- /.container-fluid -->
    </nav>
    <main class="main-wrapper">
        <div class="">
            {% block content %} {% endblock %}
        </div>
    </main>
</body>

</html>

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %} {% block title %}Home{% endblock %} {% block content %} {% if user.is_authenticated %} Hi {{ user.username }}!
<p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a> {% endif %} {% endblock %}